
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `endoj`=list(
        `type`="software", 
        `author`="Gallucci, M., Zagaria, A.", 
        `year`=2022, 
        `title`="ENDOj: Jamovi module for instrumental variables two stages regresssion", 
        `publisher`="[jamovi module]. For help please visit https://endojamovi.github.io/", 
        `url`="https://endojamovi.github.io/"), 
    `ivreg`=list(
        `type`="software", 
        `title`="ivreg: Instrumental-Variables Regression by '2SLS', '2SM', or '2SMM', with Diagnostics", 
        `author`="Fox, J., Kleiber, C., Zeileis, A., Kuschnig, N.", 
        `year`=2021, 
        `publisher`="[R Package]. Retrieved from https://CRAN.R-project.org/package=ivreg", 
        `url`="https://CRAN.R-project.org/package=ivreg"))
